### ISSUE TITLE
PageBoyViewController freeze when push a new VC during auto-scrolling transition

### ISSUE THREAD

**Issue by nsmag** [uias/Pageboy#166]
If push a VC when the auto-scroll transition start, when back to the PageBoyVC, it will not respond to scroll/tap and autoScroller stop working too.

This is only happen with autoScroller. It's working fine with user-scroll

**Comment by corbinhudson** [comment]
I have the same issue except I am not using auto scroll (direct). I load a 3 paged table view, and when the user clicks on tab if it is empty (for first time) it pushes to new VC. When user hits back the view is frozen and will not respond

**Comment by nsmag** [comment]
I'm not sure if this happen because the completion block of `scrollToPage` is not called when pushing a new VC during animation

```swift
...
                self.isScrollingAnimated = animated
                let direction = directionForPageScroll(to: page, index: rawIndex)
                
                let transitionCompletion: TransitionOperation.Completion = { (finished) in
                    if finished {
                        let isVertical = self.navigationOrientation == .vertical
                        let currentPosition = CGPoint(x: isVertical ? 0.0 : CGFloat(rawIndex),
                                                      y: isVertical ? CGFloat(rawIndex) : 0.0)
                        self.currentPosition = currentPosition
                        self.currentIndex = rawIndex
                        
                        // if not animated call position delegate update manually
                        if !animated {
                            self.delegate?.pageboyViewController(self,
                                                                 didScrollTo: currentPosition,
                                                                 direction: direction,
                                                                 animated: animated)
                        }
                    }
                    
                    self.autoScroller.didFinishScrollIfEnabled()
                    completion?(viewController, animated, finished)
                    self.isScrollingAnimated = false
                }
...
```

**Comment by corbinhudson** [comment]
I am using Tabman in combination with Pageboy, I made no changes to my code except update pod and the error occurred. Reverted Pagepoy to 2.3 & Tabamn to 1.5.2 and now is working no problem. Will wait for fix

**Comment by msaps** [comment]
@corbinhudson @nsmag okay will check it out! Looks like it was probably a regression with updating the transition stuff in 2.4

**Comment by msaps** [comment]
@nsmag @corbinhudson could you try [2.5.3](https://github.com/uias/Pageboy/releases/tag/2.5.3) and see if that fixes the issues you're having?

I managed to reproduce issues when pushing a new VC during an animated transition - which are now fixed as seen below: 

![interruption fix](https://user-images.githubusercontent.com/3515448/42886265-61c3e596-8aa3-11e8-83d5-2ff9c263a626.gif)

**Comment by nsmag** [comment]
@msaps looks like the issue still exists.

I created a demo [here](https://github.com/nsmag/demo-pageboy-transition-issue)

In the demo, the first VC is a Pageboy with 3 VCs (red, yellow, green)
then I use dispatch queue to push a new VC when pageboy starting transition, press back and the pageboy VC will freeze.

![demo-pageboy-transition-issue](https://user-images.githubusercontent.com/2218446/42930588-9b373ec6-8b67-11e8-8cf7-930ffe355750.gif)

**Comment by msaps** [comment]
@nsmag just released [2.5.4](https://github.com/uias/Pageboy/releases/tag/2.5.4) which should resolve the issue! Hopefully second time is the charm. 😄 

The demo project really helped! 

![interruption-fix](https://user-images.githubusercontent.com/3515448/42934833-6f03651a-8b48-11e8-8277-50c9d984f5e1.gif)

**Comment by nsmag** [comment]
@msaps  It still freeze if pushing at the right moment
let's set timer in the demo to 1.9

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1.9) {...
```

I updated the demo repo.

**Comment by msaps** [comment]
@nsmag are you using [2.5.4](
https://github.com/uias/Pageboy/releases/tag/2.5.4)? The demo project works fine for me with the 1.9 delay on 2.5.4.

**Comment by nsmag** [comment]
@msaps Sorry I forgot to `pod update`. The demo works fine.

I'll test it on my project.

**Comment by nsmag** [comment]
@msaps 
If the PageboyVC is in table view, it'll freeze.
I'm not sure if I did anything wrong

I updated the [demo repo](https://github.com/nsmag/demo-pageboy-transition-issue):
the first VC is a UITableViewController with PageBoyViewController in it.

**Comment by corbinhudson** [comment]
I tested in my project with updates, working now thanks!

**Comment by msaps** [comment]
@nsmag An additional tweak I want to make is to pause the auto scrolling when `viewWillDisappear()` is received and restarting on `viewDidAppear` - as currently the auto scrolling will continue when offscreen. 

With your implementation in the `UITableViewCell` however, the `PageboyViewController` won't receive the correct lifecycle events as it is never added as a child view controller. This is probably why this issue is reproducible as it relies on `viewWillAppear` and other lifecycle events. I would recommend implementing this differently (perhaps the parent VC owns the child `PageboyViewController`s and provides them to the cells rather than the cell owning it?)

**Comment by nsmag** [comment]
@msaps I totally forgot about child VC. I'll try another test. thanks!

**Comment by nsmag** [comment]
@msaps `addChildViewController()` fix my issue
Thanks!

**Comment by ahmedk92** [comment]
Freezes on iPhone 6s Plus iOS 12.3.1 with scrollToPage.

**Comment by Johnathan-Aretos** [comment]
I know this issue is closed but I also just came across this issue, on v3.4.0. 

When I call `scrollToPage(.next, animated: true)` it will freeze the screen after completion. But normal scrolling (user initiated) works fine. If a user scrolls to the next screen and they click the back button for example `scrollToPage(.previous, animated: true)` is called and will auto scroll to the previous page and works fine. Only using `.next` will cause a freeze. I'll do some investigating over the next day and see what I can find.
